#!/bin/sh

if [ `id -u` -ne '0' ]; then
  echo "This script must be run as root" >&2
  exit 1
fi

log=/var/log/watch_ip_change.log
monitor_pid_file=/run/watch_ip_change_monitor.pid
pid_file=/run/watch_ip_change.pid
pipe_file=/run/watch_ip_change.pipe

start() {
  mkfifo $pipe_file

  /usr/share/lamp/watch_ip_change_process.sh < $pipe >> $log 2>&1 &
  pid=$!
  echo $pid > $pid_file

  ip monitor address < /dev/null > $pipe 2> /dev/null &
  pid=$!
  echo $pid > $monitor_pid_file
}

stop() {
  kill $(cat $monitor_pid_file)
  kill $(cat $pid_file)
  rm $pipe
}

case "$1" in
  start)
        start;
        ;;
  stop)
        stop;
        ;;
  restart)
        stop;
        start;
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
